GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Harry's pasta tricks", 
    "author": "Harry D.", 
    "url": "place.mesta", 
    "likes": "5" 
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Perry's rasta kicks", 
    "author": "Perry M. MD", 
    "url": "place.mesta", 
    "likes": "10" 
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
  "likes": 10
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/5a422a851b54a676234d17f7

//DELETE http://localhost:3003/api/blogs/hwm6n&Y%¤"VIBl45n)BK(JHVGVfdfhvjb


###

DELETE http://localhost:3003/api/blogs/65faa6c65426b5aa9701727e


###

PUT http://localhost:3003/api/blogs/65faa6c65426b5aa97017280
Content-Type: application/json

{
  "title": "updated 1",
  "author": "updated 2",
  "url": "updated 3",
  "likes": 4
}


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "userName": "LissuLee",
  "name": "Liisa Läntti",
  "password": "crypt1c"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "userName": "Jim Johnson",
  "name": "Jalmari Jalonen",
  "password": "s4lkku"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "userName": "X",
  "name": "Xibit",
  "password": "yo"
}

###

GET http://localhost:3003/api/users