GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Harry's pasta tricks", 
    "author": "Harry D.", 
    "url": "place.mesta", 
    "likes": "5" 
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Perry's rasta kicks", 
    "author": "Perry M. MD", 
    "url": "place.mesta", 
    "likes": "10" 
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
  "likes": 10
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0,
  // userId = Liisa Läntti
  "userId": "65fd759e2f4a8d98ccfbb759"
}

###

PUT http://localhost:3003/api/blogs/65faa6c65426b5aa97017280
Content-Type: application/json

{
  "title": "updated 1",
  "author": "updated 2",
  "url": "updated 3",
  "likes": 4
}


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "LissuLee",
  "name": "Liisa Läntti",
  "password": "crypt1c"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Jim Johnson",
  "name": "Jalmari Jalonen",
  "password": "s4lkku"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "X",
  "name": "Xibit",
  "password": "yo"
}

###

GET http://localhost:3003/api/users

###

post http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "LissuLee",
  "password": "crypt1c"
}